### ISSUE TITLE
NamespaceSpacing sniff breaks with file header

### ISSUE THREAD

**Issue by alcaeus** [slevomat/coding-standard#727] opened 2019-07-26 07:38 UTC
Cross-referencing #585 but I didn't want to dig out an old issue. I've noticed an error with the `SlevomatCodingStandard.Namespaces.NamespaceSpacing` sniff. The file in question is this: https://github.com/mongodb/mongo-php-library/blob/039a6945088c84e8a35ea9462f2d9f1f5f45aee6/src/Exception/UnexpectedValueException.php#L18. The configuration from the sniff is inherited from doctrine/coding-standard with default settings:
```xml
<rule ref="SlevomatCodingStandard.Namespaces.NamespaceSpacing"/>
```

Running phpcs notes an error:
```
vendor/bin/phpcs --sniffs=SlevomatCodingStandard.Namespaces.NamespaceSpacing src/Exception/UnexpectedValueException.php 
E 1 / 1 (100%)



FILE: src/Exception/UnexpectedValueException.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 18 | ERROR | [x] Expected 1 lines before namespace statement, found 2.
    |       |     (SlevomatCodingStandard.Namespaces.NamespaceSpacing.IncorrectLinesCountBeforeNamespace)
----------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Running phpcbf also causes an error:
```
vendor/bin/phpcbf --sniffs=SlevomatCodingStandard.Namespaces.NamespaceSpacing src/Exception/UnexpectedValueException.php 
E 1 / 1 (100%)



PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
src/Exception/UnexpectedValueException.php            FAILED TO FIX
----------------------------------------------------------------------
A TOTAL OF 0 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------
PHPCBF FAILED TO FIX 1 FILE
----------------------------------------------------------------------
```

**Comment by kukulich** [comment] 2019-10-29 11:02
@alcaeus Hmm, it looks the problem could be caused by bad comment. There is `/*` instead of `/**` in the file.

**Comment by alcaeus** [comment] 2019-10-29 11:26
I wouldn't call that a bad comment - it's a regular comment block. `/*` denotes comments, `/**` denotes a docblock. Quote: ([Source](https://en.wikipedia.org/wiki/PHPDoc#DocBlock)):
> A DocBlock is an extended C++-style PHP comment that begins with `/**` and has an `*` at the beginning of every line.

**Comment by kukulich** [comment] 2019-10-29 11:44
Fixed in https://github.com/slevomat/coding-standard/commit/143d8bcaf5d7728449e754b7a716c8db4a732960

**Closed by kukulich** 2019-10-29 11:44 UTC
Labels: Bug

**Comment by alcaeus** [comment] 2019-10-29 11:56
Thanks @kukulich! ❤️
