### ISSUE TITLE
RequireCombinedAssignmentOperator breaking code on consecutive division + multiplication when not parentheses present

### ISSUE THREAD

**Issue by tolry** [slevomat/coding-standard#675] opened 2019-04-30 11:55 UTC
It could definitely be argued, that this code is missing parentheses, but still this breaks stuff. I am not sure if there is an easy way to detect these cases, but can offer to take a look at it, if that's helpful.

```php

$percent = $percent / $total * 100
# this means effectively
$percent = ($percfent / $total)  * 100

# with RequireCombinedAssignmentOperator
$percent /= $tota)  * 100
# becomes effectively
$percent = $percfent / ($total  * 100)
```

https://3v4l.org/hC6LX

**Comment by kukulich** [comment] 2019-04-30 19:37
Duplicate of https://github.com/slevomat/coding-standard/issues/649

**Closed by kukulich** 2019-04-30 19:37 UTC
Labels: Duplicate

**Comment by tolry** [comment] 2019-05-02 16:51
Sorry about that, I did miss that one.
