### ISSUE TITLE
Class 'PHPStan\PhpDocParser\Parser\TokenIterator' not found

### ISSUE THREAD

**Issue by StevenRoan** [slevomat/coding-standard#1016] opened 2020-05-24 03:01 UTC
Similar issue as in #632 

The  version of packages used are:
```
phpstan/phpdoc-parser                 0.3.5
slevomat/coding-standard              6.2.0 / 6.3.6 (Both are not working)
PHP_CodeSniffer 3.5.5
php 7.4.4
```
My current workaround is downgrading the slevomat/coding-standard to 5.0.3 and it works fine now.

**Comment by kukulich** [comment] 2020-05-24 06:08
Duplicate of #632

**Closed by kukulich** 2020-05-24 06:08 UTC
