### ISSUE TITLE
UselessVariable: false positives with returns and assigments in ifs

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#423] opened 2018-08-27 18:00 UTC
```php
        if ($foo = $this->bar($quo)) {
            $this->baz = true;

            return $foo;
        }
```

Get "fixed" into:

```php
        if (return $this->bar($quo)) {
            $this->baz = true;
        }
```

**Comment by kukulich** [comment] 2018-08-27 18:14
It should be already fixed: 
https://github.com/slevomat/coding-standard/issues/419

**Comment by carusogabriel** [comment] 2018-08-27 18:27
Gonna test the dev version and close if it's fixed :smile:

**Comment by kukulich** [comment] 2018-08-27 21:50
@carusogabriel I'm not able to reproduce it.

**Comment by carusogabriel** [comment] 2018-08-27 22:54
It was fixed with #419 indeed :)

**Comment by carusogabriel** [comment] 2018-08-28 18:34
Looks like it wasn't. Code to reproduce:
```php
        if ($foo = $this->foo->bar($baz['_id'], $quoz)) {
            $this->bazo->lotus('Message');

            return $foo;
        }
```

**Comment by carusogabriel** [comment] 2018-08-28 18:35
And invalidate my comment https://github.com/slevomat/coding-standard/issues/423#issuecomment-416395006, it wasn't fixed.

**Comment by kukulich** [comment] 2018-08-29 20:37
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/2654744cbcb7c25dbaafce3bc6a91f87c71c27a4

**Closed by kukulich** 2018-08-29 20:37 UTC
Labels: Bug
