### ISSUE TITLE
Remove unecessary variable when followed by a return

### ISSUE THREAD

**Issue by carusogabriel** [slevomat/coding-standard#392] opened 2018-07-25 01:26 UTC
I don't know if this is a valid rule for `UnusedVariable`, maybe `UnecessaryVariable`, but:

```php
function returnString(): string {
    $string = 'foo';

    return $string;
}

// vs.

function returnString(): string {
    return 'foo';
}
```

**Comment by Majkl578** [comment] 2018-07-25 01:41
Duplicate of https://github.com/slevomat/coding-standard/issues/373 (where you actually added 🎉).

**Closed** 2018-07-25 02:07 UTC
