### ISSUE TITLE
Out of memory errors (probably) because of heredoc syntax

### ISSUE THREAD

**Issue by kejwmen** [slevomat/coding-standard#535] opened 2018-10-23 16:08 UTC
Hi,
I use doctrine coding standard (5.0) and noticed some issues with heredoc syntax. After quick debugging it looks like crashes are related to one of your (great and very helpful) sniffs.

This is my reproducer:

```
<?php

declare(strict_types=1);

final class Reproducer
{
    public function hereDocExample()
    {
        $var = [
            'foo',
            <<<EATING_MEMORY
    BAR
EATING_MEMORY,
        ];
    }
}
```

Without trailing comma after `EATING_MEMORY` it works fine.

When I runn `vendor/bin/phpcs --standard=Doctrine -p -vvv Reproducer.php` it freezes at: `Processing SlevomatCodingStandard\Sniffs\Exceptions\ReferenceThrowableOnlySniff`.

Thanks for a great set of sniffs :)

**Comment by kejwmen** [comment] 2018-10-23 16:33
@Majkl578 noticed that this code is wrong (trailing comma is not allowed there), but that change was made by `phpcbf`, so it looks like sniff that adds comma after last array element (?) should be aware of that?

**Comment by kukulich** [comment] 2018-10-23 16:52
Yes, the comma is not allowed there in PHP 7.2 but it’s ok in PHP 7.3 so I decided not to fix it.

**Comment by Majkl578** [comment] 2018-10-23 17:04
I think it should be fixed, inifinite loop is very bad. Also no one is really going to require PHP 7.3 and <7.3 is required for at least until 7.4.

Additionally in 7.3 it should be formatted this way:
```php
        $var = [
            'foo',
            <<<EATING_MEMORY
                BAR
            EATING_MEMORY,
        ];
```

**Comment by kejwmen** [comment] 2018-10-23 17:07
Is it possible to change this behavior for php <7.3?

Formatting this manually will cause errors from `Squiz.Arrays.ArrayDeclaration.SpaceBeforeComma` sniff.

I can disable sniffs causing trouble for lines using heredoc, but fixing this would be great.

**Comment by kukulich** [comment] 2018-10-23 17:37
@Majkl578 yes, I will fix the infinite loop but probably not fix the comma after heredoc.

**Comment by kukulich** [comment] 2018-10-23 17:43
@kejwmen you can save the heredoc to variable as hotfix

**Comment by kejwmen** [comment] 2018-10-24 12:31
ok, thanks!

**Comment by kukulich** [comment] 2018-11-02 20:18
@kejwmen 

It does not freeze. It fails because of internal error:

```
 1 | ERROR | [ ] An error occurred during processing; checking has been aborted. The error message was: Undefined index: scope_closer in
   |       |     .\vendor\slevomat\coding-standard\SlevomatCodingStandard\Helpers\UseStatementHelper.php on line 156
```

This internal error is caused by bug in PHPCS itself. The `T_CLASS` token is broken when you put comma after HEREDOC. Please report the bug in PHPCS repository. Thanks.

**Closed by kukulich** 2018-11-02 20:18 UTC
Labels: Invalid

**Comment by paslandau** [comment] 2019-01-02 19:17
@kukulich

I just ran into the same problem (running on php 7.2). The process doesn't die and doesn't throw an exception for me. It goes into an infinite loop (as described above) which is really hard to debug when you run phpcs on a bigger codebase and "just nothing happens".

Imho this shouldn't happen "by default", even if it's a bug in PHPCS. Possible "quickfixes": 
- add warning in documentation that this might happen when running <php7.3
- disable auto-fixing for `SlevomatCodingStandard.Arrays.TrailingArrayComma` (maybe enable via property?)
- exclude HEREDOC especially from `SlevomatCodingStandard.Arrays.TrailingArrayComma` (not sure how "quick" this is...)

Example:

Ruleset
==
```
<?xml version="1.0"?>
<ruleset name="Error">
    <!-- relative path from PHPCS source location -->
    <config name="installed_paths" value="../../slevomat/coding-standard"/>
    <!-- phpcbf "introduces" the error-->
    <rule ref="SlevomatCodingStandard.Arrays.TrailingArrayComma"/>
    <!-- this is one of the rules that leads to an infinite loop -->
    <rule ref="SlevomatCodingStandard.Namespaces.UseSpacing"/>
</ruleset>
```

Code
==
```php
<?php

class foo
{
    public function foo()
    {
        return [
            "hello",
            "baz",
            <<<CONTENT
foo
CONTENT
        ];
    }
}
```

Relevant logs
```
        => Changeset started by SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff (line 62)
                Q: SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff (line 63) replaced token 36 (T_END_HEREDOC) "CONTENT"
=> "CONTENT,"
                A: SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff (line 64) replaced token 36 (T_END_HEREDOC) "CONTENT"
=> "CONTENT,"
        => Changeset ended: 1 changes applied
        => Fixing file: 1/1 violations remaining [made 1 pass]...       * fixed 1 violations, starting loop 2 *
```

Complete output
```
root@c842fb6554b4:/var/www/current# vendor/bin/phpcbf test2.php --standard=qa/phpcs/error.xml -vvv
Processing ruleset /var/www/current/qa/phpcs/error.xml
        => set config value installed_paths: ../../slevomat/coding-standard
        Processing rule "SlevomatCodingStandard.Namespaces.UseSpacing"
                => /var/www/current/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UseSpacingSniff.php
        Processing rule "SlevomatCodingStandard.Arrays.TrailingArrayComma"
                => /var/www/current/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Arrays/TrailingArrayCommaSniff.php
=> Ruleset processing complete; included 2 sniffs and excluded 0
Registered SlevomatCodingStandard\Sniffs\Namespaces\UseSpacingSniff
Registered SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff
Creating file list... DONE (1 files in queue)
Changing into directory /var/www/current
Processing test2.php
        *** START PHP TOKENIZING ***
        Process token [0]: T_OPEN_TAG => <?php\n
        Process token [1]: T_WHITESPACE => \n
        Process token [2]: T_CLASS => class
        Process token [3]: T_WHITESPACE => ·
        Process token [4]: T_STRING => foo
        Process token [5]: T_WHITESPACE => \n
        Process token  6 : T_OPEN_CURLY_BRACKET => {
        Process token [7]: T_WHITESPACE => \n····
        Process token [8]: T_PUBLIC => public
        Process token [9]: T_WHITESPACE => ·
        Process token [10]: T_FUNCTION => function
        Process token [11]: T_WHITESPACE => ·
        Process token [12]: T_STRING => foo
        Process token  13 : T_OPEN_PARENTHESIS => (
        Process token  14 : T_CLOSE_PARENTHESIS => )
        Process token [15]: T_WHITESPACE => \n····
        Process token  16 : T_OPEN_CURLY_BRACKET => {
        Process token [17]: T_WHITESPACE => \n········
        Process token [18]: T_RETURN => return
        Process token [19]: T_WHITESPACE => ·
        Process token  20 : T_OPEN_SQUARE_BRACKET => [
        Process token [21]: T_WHITESPACE => \n············
        Process token [22]: T_CONSTANT_ENCAPSED_STRING => "hello"
        Process token  23 : T_COMMA => ,
        Process token [24]: T_WHITESPACE => \n············
        Process token [25]: T_CONSTANT_ENCAPSED_STRING => "baz"
        Process token  26 : T_COMMA => ,
        Process token [27]: T_WHITESPACE => \n············
        Process token [28]: T_START_HEREDOC => <<<CONTENT\n
        Process token [31]: T_WHITESPACE => \n········
        Process token  32 : T_CLOSE_SQUARE_BRACKET => ]
        Process token  33 : T_SEMICOLON => ;
        Process token [34]: T_WHITESPACE => \n····
        Process token  35 : T_CLOSE_CURLY_BRACKET => }
        Process token [36]: T_WHITESPACE => \n
        Process token  37 : T_CLOSE_CURLY_BRACKET => }
        Process token [38]: T_WHITESPACE => \n
        *** END PHP TOKENIZING ***
        *** START TOKEN MAP ***
        => Found curly bracket opener at 6
                => Found curly bracket opener at 18
                        => Found square bracket opener at 23
                        => Found square bracket closer at 39 for 23
                => Found curly bracket closer at 43 for 18
        => Found curly bracket closer at 45 for 6
        *** END TOKEN MAP ***
        *** START SCOPE MAP ***
        Start scope map at 2:T_CLASS => class
        => Begin scope map recursion at token 2 with depth 1
        Process token 3 on line 3 []: T_WHITESPACE => ·
        Process token 4 on line 3 []: T_STRING => foo
        Process token 5 on line 3 []: T_WHITESPACE => \n
        Process token 6 on line 4 []: T_OPEN_CURLY_BRACKET => {
        => Found scope opener for 2:T_CLASS
        Process token 7 on line 4 [opener:6;]: T_WHITESPACE => \n
        Process token 8 on line 5 [opener:6;]: T_WHITESPACE => ····
        Process token 9 on line 5 [opener:6;]: T_PUBLIC => public
        Process token 10 on line 5 [opener:6;]: T_WHITESPACE => ·
        Process token 11 on line 5 [opener:6;]: T_FUNCTION => function
        * token is an opening condition *
        * searching for opener *
                => Begin scope map recursion at token 11 with depth 2
                Process token 12 on line 5 []: T_WHITESPACE => ·
                Process token 13 on line 5 []: T_STRING => foo
                Process token 14 on line 5 []: T_OPEN_PARENTHESIS => (
                Process token 15 on line 5 []: T_CLOSE_PARENTHESIS => )
                Process token 16 on line 5 []: T_WHITESPACE => \n
                Process token 17 on line 6 []: T_WHITESPACE => ····
                Process token 18 on line 6 []: T_OPEN_CURLY_BRACKET => {
                => Found scope opener for 11:T_FUNCTION
                Process token 19 on line 6 [opener:18;]: T_WHITESPACE => \n
                Process token 20 on line 7 [opener:18;]: T_WHITESPACE => ········
                Process token 21 on line 7 [opener:18;]: T_RETURN => return
                Process token 22 on line 7 [opener:18;]: T_WHITESPACE => ·
                Process token 23 on line 7 [opener:18;]: T_OPEN_SQUARE_BRACKET => [
                Process token 24 on line 7 [opener:18;]: T_WHITESPACE => \n
                Process token 25 on line 8 [opener:18;]: T_WHITESPACE => ············
                Process token 26 on line 8 [opener:18;]: T_CONSTANT_ENCAPSED_STRING => "hello"
                Process token 27 on line 8 [opener:18;]: T_COMMA => ,
                Process token 28 on line 8 [opener:18;]: T_WHITESPACE => \n
                Process token 29 on line 9 [opener:18;]: T_WHITESPACE => ············
                Process token 30 on line 9 [opener:18;]: T_CONSTANT_ENCAPSED_STRING => "baz"
                Process token 31 on line 9 [opener:18;]: T_COMMA => ,
                Process token 32 on line 9 [opener:18;]: T_WHITESPACE => \n
                Process token 33 on line 10 [opener:18;]: T_WHITESPACE => ············
                Process token 34 on line 10 [opener:18;]: T_START_HEREDOC => <<<CONTENT\n
                * token is an opening condition *
                * searching for opener *
                        => Begin scope map recursion at token 34 with depth 3
                        Process token 35 on line 11 [opener:34;]: T_HEREDOC => foo\n
                        Process token 36 on line 12 [opener:34;]: T_END_HEREDOC => CONTENT
                        => Found scope closer (36:T_END_HEREDOC) for 34:T_START_HEREDOC
                Process token 37 on line 12 [opener:18;]: T_WHITESPACE => \n
                Process token 38 on line 13 [opener:18;]: T_WHITESPACE => ········
                Process token 39 on line 13 [opener:18;]: T_CLOSE_SQUARE_BRACKET => ]
                Process token 40 on line 13 [opener:18;]: T_SEMICOLON => ;
                Process token 41 on line 13 [opener:18;]: T_WHITESPACE => \n
                Process token 42 on line 14 [opener:18;]: T_WHITESPACE => ····
                Process token 43 on line 14 [opener:18;]: T_CLOSE_CURLY_BRACKET => }
                => Found scope closer (43:T_CLOSE_CURLY_BRACKET) for 11:T_FUNCTION
        Process token 44 on line 14 [opener:6;]: T_WHITESPACE => \n
        Process token 45 on line 15 [opener:6;]: T_CLOSE_CURLY_BRACKET => }
        => Found scope closer (45:T_CLOSE_CURLY_BRACKET) for 2:T_CLASS
        *** END SCOPE MAP ***
        *** START LEVEL MAP ***
        Process token 0 on line 1 [col:1;len:5;lvl:0;]: T_OPEN_TAG => <?php\n
        Process token 1 on line 2 [col:1;len:0;lvl:0;]: T_WHITESPACE => \n
        Process token 2 on line 3 [col:1;len:5;lvl:0;]: T_CLASS => class
        Process token 3 on line 3 [col:6;len:1;lvl:0;]: T_WHITESPACE => ·
        Process token 4 on line 3 [col:7;len:3;lvl:0;]: T_STRING => foo
        Process token 5 on line 3 [col:10;len:0;lvl:0;]: T_WHITESPACE => \n
        Process token 6 on line 4 [col:1;len:1;lvl:0;]: T_OPEN_CURLY_BRACKET => {
        => Found scope opener for 2:T_CLASS
                * level increased *
                * token 2:T_CLASS added to conditions array *
                Process token 7 on line 4 [col:2;len:0;lvl:1;conds;T_CLASS;]: T_WHITESPACE => \n
                Process token 8 on line 5 [col:1;len:4;lvl:1;conds;T_CLASS;]: T_WHITESPACE => ····
                Process token 9 on line 5 [col:5;len:6;lvl:1;conds;T_CLASS;]: T_PUBLIC => public
                Process token 10 on line 5 [col:11;len:1;lvl:1;conds;T_CLASS;]: T_WHITESPACE => ·
                Process token 11 on line 5 [col:12;len:8;lvl:1;conds;T_CLASS;]: T_FUNCTION => function
                Process token 12 on line 5 [col:20;len:1;lvl:1;conds;T_CLASS;]: T_WHITESPACE => ·
                Process token 13 on line 5 [col:21;len:3;lvl:1;conds;T_CLASS;]: T_STRING => foo
                Process token 14 on line 5 [col:24;len:1;lvl:1;conds;T_CLASS;]: T_OPEN_PARENTHESIS => (
                Process token 15 on line 5 [col:25;len:1;lvl:1;conds;T_CLASS;]: T_CLOSE_PARENTHESIS => )
                Process token 16 on line 5 [col:26;len:0;lvl:1;conds;T_CLASS;]: T_WHITESPACE => \n
                Process token 17 on line 6 [col:1;len:4;lvl:1;conds;T_CLASS;]: T_WHITESPACE => ····
                Process token 18 on line 6 [col:5;len:1;lvl:1;conds;T_CLASS;]: T_OPEN_CURLY_BRACKET => {
                => Found scope opener for 11:T_FUNCTION
                        * level increased *
                        * token 11:T_FUNCTION added to conditions array *
                        Process token 19 on line 6 [col:6;len:0;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => \n
                        Process token 20 on line 7 [col:1;len:8;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ········
                        Process token 21 on line 7 [col:9;len:6;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_RETURN => return
                        Process token 22 on line 7 [col:15;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ·
                        Process token 23 on line 7 [col:16;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_OPEN_SQUARE_BRACKET => [
                        Process token 24 on line 7 [col:17;len:0;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => \n
                        Process token 25 on line 8 [col:1;len:12;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ············
                        Process token 26 on line 8 [col:13;len:7;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_CONSTANT_ENCAPSED_STRING => "hell
o"
                        Process token 27 on line 8 [col:20;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_COMMA => ,
                        Process token 28 on line 8 [col:21;len:0;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => \n
                        Process token 29 on line 9 [col:1;len:12;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ············
                        Process token 30 on line 9 [col:13;len:5;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_CONSTANT_ENCAPSED_STRING => "baz"
                        Process token 31 on line 9 [col:18;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_COMMA => ,
                        Process token 32 on line 9 [col:19;len:0;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => \n
                        Process token 33 on line 10 [col:1;len:12;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ············
                        Process token 34 on line 10 [col:13;len:10;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_START_HEREDOC => <<<CONTENT\n
                        => Found scope opener for 34:T_START_HEREDOC
                                * level increased *
                                * token 34:T_START_HEREDOC added to conditions array *
                                Process token 35 on line 11 [col:1;len:3;lvl:3;conds;T_CLASS,T_FUNCTION,T_START_HEREDOC;]: T_HEREDOC =
> foo\n
                                Process token 36 on line 12 [col:1;len:7;lvl:3;conds;T_CLASS,T_FUNCTION,T_START_HEREDOC;]: T_END_HERED
OC => CONTENT
                                => Found scope closer for 34:T_START_HEREDOC
                                * token T_START_HEREDOC removed from conditions array *
                                * level decreased *
                        Process token 37 on line 12 [col:8;len:0;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => \n
                        Process token 38 on line 13 [col:1;len:8;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ········
                        Process token 39 on line 13 [col:9;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_CLOSE_SQUARE_BRACKET => ]
                        Process token 40 on line 13 [col:10;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_SEMICOLON => ;
                        Process token 41 on line 13 [col:11;len:0;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => \n
                        Process token 42 on line 14 [col:1;len:4;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_WHITESPACE => ····
                        Process token 43 on line 14 [col:5;len:1;lvl:2;conds;T_CLASS,T_FUNCTION;]: T_CLOSE_CURLY_BRACKET => }
                        => Found scope closer for 18:T_OPEN_CURLY_BRACKET
                        * token T_FUNCTION removed from conditions array *
                        * level decreased *
                Process token 44 on line 14 [col:6;len:0;lvl:1;conds;T_CLASS;]: T_WHITESPACE => \n
                Process token 45 on line 15 [col:1;len:1;lvl:1;conds;T_CLASS;]: T_CLOSE_CURLY_BRACKET => }
                => Found scope closer for 6:T_OPEN_CURLY_BRACKET
                * token T_CLASS removed from conditions array *
                * level decreased *
        Process token 46 on line 15 [col:2;len:0;lvl:0;]: T_WHITESPACE => \n
        *** END LEVEL MAP ***
        *** START ADDITIONAL PHP PROCESSING ***
        * token 23 on line 7 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 39 on line 13 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        *** END ADDITIONAL PHP PROCESSING ***
[PHP => 47 tokens in 15 lines]...
        *** START TOKEN PROCESSING ***
                Process token 0: T_OPEN_TAG => <?php\n
                        Processing SlevomatCodingStandard\Sniffs\Namespaces\UseSpacingSniff... DONE in 0.0484 seconds
                Process token 1: T_WHITESPACE => \n
                Process token 2: T_CLASS => class
                Process token 3: T_WHITESPACE => ·
                Process token 4: T_STRING => foo
                Process token 5: T_WHITESPACE => \n
                Process token 6: T_OPEN_CURLY_BRACKET => {
                Process token 7: T_WHITESPACE => \n
                Process token 8: T_WHITESPACE => ····
                Process token 9: T_PUBLIC => public
                Process token 10: T_WHITESPACE => ·
                Process token 11: T_FUNCTION => function
                Process token 12: T_WHITESPACE => ·
                Process token 13: T_STRING => foo
                Process token 14: T_OPEN_PARENTHESIS => (
                Process token 15: T_CLOSE_PARENTHESIS => )
                Process token 16: T_WHITESPACE => \n
                Process token 17: T_WHITESPACE => ····
                Process token 18: T_OPEN_CURLY_BRACKET => {
                Process token 19: T_WHITESPACE => \n
                Process token 20: T_WHITESPACE => ········
                Process token 21: T_RETURN => return
                Process token 22: T_WHITESPACE => ·
                Process token 23: T_OPEN_SHORT_ARRAY => [
                        Processing SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff... DONE in 0.0003 seconds
                Process token 24: T_WHITESPACE => \n
                Process token 25: T_WHITESPACE => ············
                Process token 26: T_CONSTANT_ENCAPSED_STRING => "hello"
                Process token 27: T_COMMA => ,
                Process token 28: T_WHITESPACE => \n
                Process token 29: T_WHITESPACE => ············
                Process token 30: T_CONSTANT_ENCAPSED_STRING => "baz"
                Process token 31: T_COMMA => ,
                Process token 32: T_WHITESPACE => \n
                Process token 33: T_WHITESPACE => ············
                Process token 34: T_START_HEREDOC => <<<CONTENT\n
                Process token 35: T_HEREDOC => foo\n
                Process token 36: T_END_HEREDOC => CONTENT
                Process token 37: T_WHITESPACE => \n
                Process token 38: T_WHITESPACE => ········
                Process token 39: T_CLOSE_SHORT_ARRAY => ]
                Process token 40: T_SEMICOLON => ;
                Process token 41: T_WHITESPACE => \n
                Process token 42: T_WHITESPACE => ····
                Process token 43: T_CLOSE_CURLY_BRACKET => }
                Process token 44: T_WHITESPACE => \n
                Process token 45: T_CLOSE_CURLY_BRACKET => }
                Process token 46: T_WHITESPACE => \n
        *** END TOKEN PROCESSING ***
        *** START SNIFF PROCESSING REPORT ***
        SlevomatCodingStandard\Sniffs\Namespaces\UseSpacingSniff: 0.0484 secs
        SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff: 0.0003 secs
        *** END SNIFF PROCESSING REPORT ***
DONE in 238ms (1 fixable violations)
        => Fixing file: 1/1 violations remaining---START FILE CONTENT---
 1|<?php
 2|
 3|class foo
 4|{
 5|    public function foo()
 6|    {
 7|        return [
 8|            "hello",
 9|            "baz",
10|            <<<CONTENT
11|foo
12|CONTENT
13|        ];
14|    }
15|}
16|
--- END FILE CONTENT ---
        => Changeset started by SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff (line 62)
                Q: SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff (line 63) replaced token 36 (T_END_HEREDOC) "CONTENT"
=> "CONTENT,"
                A: SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff (line 64) replaced token 36 (T_END_HEREDOC) "CONTENT"
=> "CONTENT,"
        => Changeset ended: 1 changes applied
        => Fixing file: 1/1 violations remaining [made 1 pass]...       * fixed 1 violations, starting loop 2 *
---START FILE CONTENT---
 1|<?php
 2|
 3|class foo
 4|{
 5|    public function foo()
 6|    {
 7|        return [
 8|            "hello",
 9|            "baz",
10|            <<<CONTENT
11|foo
12|CONTENT,
13|        ];
14|    }
15|}
16|
--- END FILE CONTENT ---

... // here it "hangs"
```

**Comment by paslandau** [comment] 2019-01-03 08:01
As for 
> This internal error is caused by bug in PHPCS itself. The T_CLASS token is broken when you put comma after HEREDOC. Please report the bug in PHPCS repository. Thanks.

There is https://github.com/squizlabs/PHP_CodeSniffer/issues/2142 which kinda sounds like the problem we're facing here. Unfortunately, the applied fix only affects a particular sniff (see https://github.com/squizlabs/PHP_CodeSniffer/commit/a06ff3b2893f4374e6e4c7c5dc4a0ef606d177ee and doesn't fix the "root" cause from what I understand).

Does that help?
