### ISSUE TITLE
SlevomatCodingStandard.PHP.DisallowDirectMagicInvokeCall fixer breaks code

### ISSUE THREAD

**Issue by mabar** [slevomat/coding-standard#1582] opened 2023-06-15 11:52 UTC
For __invoke called on an object property, parenthesis should be added so it does not change property access to a method call

`$less = $this->filter->__invoke($filtered, $this->compiler, $file);` was changed to
`$less = $this->filter($filtered, $this->compiler, $file);` instead of
`$less = ($this->filter)($filtered, $this->compiler, $file);`

**Comment by kukulich** [comment] 2023-06-15 11:53
Duplicate of #1319

**Closed by kukulich** 2023-06-15 11:53 UTC
