### ISSUE TITLE
Regression: Useless* sniffs no longer supports attribute comments that start on a new line since 8.13.0

### ISSUE THREAD

**Issue by TravisCarden** [slevomat/coding-standard#1593] opened 2023-07-05 18:09 UTC
The doc comment parsing in https://github.com/slevomat/coding-standard/releases/tag/8.13.0 seems to have introduced a regression whereby `@param` attributes with comments that begin on a new line are incorrectly treated as useless. Here's a test case:

```php
class Example {
    /**
     * @param string $string
     *   Example comment.
     *
     * @return void
     *   Example comment.
     */
    public function test(string $string): void {}
}
```

As of `8.13.0`, this produces the following errors:

```
FILE: Example.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
  5 | ERROR | [x] Method \Example::test() has useless @param annotation for parameter $string.
    |       |     (SlevomatCodingStandard.TypeHints.ParameterTypeHint.UselessAnnotation)
  8 | ERROR | [x] Method \Example::test() has useless @return annotation. (SlevomatCodingStandard.TypeHints.ReturnTypeHint.UselessAnnotation)
 11 | ERROR | [x] Method \Example::test() does not need documentation comment. (SlevomatCodingStandard.Commenting.UselessFunctionDocComment.UselessDocComment)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

If I run PHPCBF, it removes the "offending" doc comment altogether:

```diff
 class Example {
 class Example {
-    /**
-     * @param string $string
-     *   Example comment.
-     *
-     * @return void
-     *   Example comment.
-     */
     public function test(string $string): void {}
 }
```

If I just put the attribute comments on the same line as below, it works correctly.

```php
class Example {
    /**
     * @param string $string Example comment.
     *
     * @return void Example comment.
     */
    public function test(string $string): void {}
}
```

**Comment by kukulich** [comment] 2023-07-24 09:00
Duplicate of #1589

**Closed by kukulich** 2023-07-24 09:00 UTC
Labels: PHPStan docparser
