### ISSUE TITLE
Undefined index: scope_condition in  EarlyExitSniff.php

### ISSUE THREAD

**Issue by morozov** [slevomat/coding-standard#891] opened 2020-02-04 05:43 UTC
Below are the relevant dependency versions:
```
$ composer show # truncated

doctrine/coding-standard       7.0.2   The Doctrine Coding Standard is a ...
slevomat/coding-standard       6.1.4   Slevomat Coding Standard for PHP_C...
squizlabs/php_codesniffer      3.5.4   PHP_CodeSniffer tokenizes PHP, Jav...
```

Consider the following code example:

```php
<?php

function fn1()
{
    foreach ([] as $_) { // Comment
        if (true) {
            $x = 1;
        }
    }
}
```
An attempt to fix this file makes `phpcs` crash:
```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_condition in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php on line 286 in vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php(286): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/home/morozov/P...', 286, Array)
#1 vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/EarlyExitSniff.php(65): SlevomatCodingStandard\Sniffs\ControlStructures\EarlyExitSniff->processIf(Object(PHP_CodeSniffer\Files\LocalFile), 40)
#2 vendor/squizlabs/php_codesniffer/src/Files/File.php(496): SlevomatCodingStandard\Sniffs\ControlStructures\EarlyExitSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 40)
#3 vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

**Comment by kukulich** [comment] 2020-02-04 10:49
I'm not able to reproduce it however it may be fixed with the fix https://github.com/slevomat/coding-standard/issues/890

**Comment by morozov** [comment] 2020-02-04 17:47
Not reproducible on `dev-master` (e1a40c1). Thanks, @kukulich!

**Closed** 2020-02-04 17:58 UTC
Labels: Bug
