### ISSUE TITLE
ConstantSpacing and PropertySpacing properties type error

### ISSUE THREAD

**Issue by marcoocram** [slevomat/coding-standard#873] opened 2020-01-28 13:36 UTC
I'm using ConstantSpacing and PropertySpacing sniffs and when i try to change the properties it throws an error on type hinting.

This is my configuration:

```
<rule ref="SlevomatCodingStandard.Classes.ConstantSpacing">
    <properties>
        <property name="minLinesCountBeforeWithoutComment" value="0"/>
        <property name="maxLinesCountBeforeWithoutComment" value="1"/>
    </properties>
</rule>
```

and the error:

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff::addError() must be of the type int, string given, called in /var/www/html/current/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php on line 83 and defined in /var/www/html/current/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ConstantSpacingSniff.php:22
```

I've tried using the variable names on de documentation (without $) but then it doesn't affect on sniff.

Thanks!

**Comment by kukulich** [comment] 2020-01-28 14:38
Duplicate of https://github.com/slevomat/coding-standard/pull/871

**Closed by kukulich** 2020-01-28 14:38 UTC
