### ISSUE TITLE
iterable<string, stirng> space parsing invalid

### ISSUE THREAD

**Issue by simPod** [slevomat/coding-standard#705] opened 2019-05-29 15:39 UTC
```php
function a()
{
    /** @var iterable<string, string> $x */
    $x = b();

    return $x;
}
```

This reports $x as [useless variable](https://github.com/slevomat/coding-standard#slevomatcodingstandardvariablesuselessvariable-).

```php
function a()
{
    /** @var iterable<string,string> $x */
    $x = b();

    return $x;
}
```

this does not.

Shouldn't it also process the version with space after `,`?

**Comment by kukulich** [comment] 2019-05-29 17:57
Duplicate of https://github.com/slevomat/coding-standard/issues/685

**Closed by kukulich** 2019-05-29 17:57 UTC
Labels: Duplicate
