### ISSUE TITLE
Issues when 7.2.1 is used with squizlabs/PHP_CodeSniffer 3.7

### ISSUE THREAD

**Issue by janedbal** [slevomat/coding-standard#1381] opened 2022-06-13 10:26 UTC
Hi, I assume there will be some official support in upcoming days/weeks, I just want to point out issues I found when analysing our codebase with slevomat/cs 7.2.1 and squizlabs/PHP_CodeSniffer 3.7.0:

1. [function named empty causing internal server error in FunctionHelper](https://github.com/slevomat/coding-standard/issues/1347)
2. enum case named **True** (or False) is identified as constant by `SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly.ReferenceViaFallbackGlobalName`
3. enum case named **Isset** causing internal server error `An error occurred during processing; checking has been aborted. The error message was: Undefined array key "parenthesis_closer" in RequireNullCoalesceOperatorSniff.php:69`

**Comment by janedbal** [comment] 2022-06-14 15:15
I oversimplified the case. It was a class method, which is allowed: https://3v4l.org/er5bV

**Comment by kukulich** [comment] 2022-06-17 11:39
1. There's no array access in `FunctionHelper` on line 92, so it looks like outdated Slevomat CS. I've checked branches `7.2` and `master`. Please try `master`.
2. I'm not able to reproduce it in `master` now. Please try `master`.
3. It's bug of PHPCS itself. The enum case name is tokenized as `T_ISSET` and that's wrong.

**Comment by kukulich** [comment] 2022-06-20 08:36
`empty` and `isset` are probably fixed in PHPCS itself: https://github.com/squizlabs/PHP_CodeSniffer/pull/3610

**Comment by janedbal** [comment] 2022-06-20 13:32
Seems like 

```
"slevomat/coding-standard": "dev-master",
"squizlabs/php_codesniffer": "3.7.1",
```

works fine. Thank you!

**Closed** 2022-06-20 13:32 UTC
