### ISSUE TITLE
DeclareStrictTypes should not be required for Interfaces 

### ISSUE THREAD

**Issue by antony-develop** [slevomat/coding-standard#1435] opened 2022-09-18 13:54 UTC
the old issue for reference - https://github.com/slevomat/coding-standard/issues/901

1) `declare(strict_types=1);` definition is useless in files containing just an interface. It is just noise when reading code.
2) It is dangerous to autofix TypeHints.DeclareStrictTypesSniff in every file (for consistency) because it can cause casting bugs.

So I think it is better to expand this sniff and add an option to ignore interface-only files.

**Comment by kukulich** [comment] 2022-09-18 14:10
Duplicate of #901

**Closed by kukulich** 2022-09-18 14:10 UTC
