### ISSUE TITLE
UnusedUses.UnusedUse false positive on phpdoc method

### ISSUE THREAD

**Issue by ohartl** [slevomat/coding-standard#290] opened 2018-02-23 16:21 UTC
```php
<?php
namespace Project/SubNamespace;

use Project/Foo;

/**
 * @method bool someMethod(Foo $foo)
 */
class Bar extends Baz
{
    // ...
}
```

Is being reported as `3 | ERROR | [x] Type Project/Foo is not used in this file. (SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse)` , but `Foo` is used in the `@method` Annotation

**Comment by Majkl578** [comment] 2018-02-23 16:42
You have to enable the `searchAnnotations` option: https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesunuseduses-

**Comment by kukulich** [comment] 2018-02-23 16:46
The option will not help. The “@method” format is really not supported now, @VasekPurchart already reported it to me privatly. I’m going to fix it next week.

**Comment by Majkl578** [comment] 2018-02-23 16:57
Interesting, because I tested it locally and it is not reported with `searchAnnotations=true`.

**Comment by kukulich** [comment] 2018-02-23 17:03
Really strange :)

**Comment by iammattcoleman** [comment] 2018-02-23 18:58
@kukulich @ohartl's example (with the namespace slashes corrected) passes on 4.4.4, but does not pass on newer versions. It also passes on 4.4.3, which is the version I'll be using for now due to this issue and #288.

**Comment by benijo** [comment] 2018-02-25 16:58
Same trouble in `property-read` annotation - with `searchAnnotations=true`

```
use App\Model\Security\User;
use Nette\Bridges\ApplicationLatte\Template;

/**
 * @property-read Template $template
 * @property-read User $user
 */
abstract class BasePresenter extends Presenter
{
```

**Comment by kukulich** [comment] 2018-02-27 10:04
@benijo Your bug should be fixed in `dev-master`.

**Comment by iammattcoleman** [comment] 2018-02-27 21:52
@kukulich I just confirmed that the issue is fixed for me in `dev-master`.

**Comment by kukulich** [comment] 2018-02-27 22:32
Support for `@method` annotation just landed in master.

**Closed by kukulich** 2018-02-27 22:32 UTC

**Comment by ohartl** [comment] 2018-03-06 16:55
@Majkl578 Note that we had `searchAnnotations=true` too, and it still reported that way. 

Thanks @kukulich . I really appreciate the time you spend fixing this.
