### ISSUE TITLE
TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification is wrong for traversible return type

### ISSUE THREAD

**Issue by vladyslavstartsev** [slevomat/coding-standard#586] opened 2019-01-13 03:35 UTC
I think that `SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification` is doing wrong sometime

I have such code
```php
/**
 * @return array<int,string>
 */
protected function getIdNameChoices(QueryBuilder $qb): array
{
    return Filter::fromQb($qb, 'id', 'name');
}
```

but I get error that says
`
@return annotation of method FooBarClass::getIdNameChoices() does not specify type hint for items of its traversable return value.
`
I think it's wrong since I've specified for items.

I think those complex return types such as `array<string, int>` or `array<int, Class>` should be supported, since, it's already supported by
- https://github.com/phpstan/phpstan
- [PHPStorm](https://blog.jetbrains.com/phpstorm/2018/09/phpstorm-2018-3-eap-183-2635-12/#psr-5-generics)
- PSR-5 is in discussion (you can see link in the phpstom blog)

**Comment by kukulich** [comment] 2019-01-13 07:13
Duplicate of 
https://github.com/slevomat/coding-standard/issues/251

**Closed by kukulich** 2019-01-13 07:13 UTC
Labels: Duplicate
