### ISSUE TITLE
UselessParenthesesSniff breaks match expression

### ISSUE THREAD

**Issue by rodolfoberrios** [slevomat/coding-standard#1150] opened 2021-01-12 16:54 UTC
Hey there,

[UselessParenthesesSniff](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/PHP/UselessParenthesesSniff.php) is breaking PHP 8 match expression by removing the parentheses `()` which generates invalid syntax.

**Comment by kukulich** [comment] 2021-01-12 17:03
Duplicate of #1138

**Closed by kukulich** 2021-01-12 17:03 UTC
