### ISSUE TITLE
ControlStructureSpacing reports false positive with comments

### ISSUE THREAD

**Issue by alcaeus** [slevomat/coding-standard#532] opened 2018-10-23 07:22 UTC
For the following code:
```php
        }

        // This is a longer comment that
        // spans across multiple lines
        return count(array_keys($context->getCurrentPath(), 'similarProducts')) >= 1;
```

the following error is reported:
```
Expected 1 lines before "return", found 2.
(SlevomatCodingStandard.ControlStructures.ControlStructureSpacing.IncorrectLinesCountBeforeControlStructure)
```

The error is marked as fixable but can't be fixed, probably because of the comment. I'd expect no error to be reported here.

**Comment by kukulich** [comment] 2018-10-23 12:29
Duplicate of #520

**Closed by kukulich** 2018-10-23 12:29 UTC
Labels: Duplicate

**Comment by alcaeus** [comment] 2018-10-23 12:32
Dang, I searched for issues but apparently not the right ones. Sorry for the noise.

**Comment by kukulich** [comment] 2018-10-23 12:33
No problem :) I'm happy I don't any new issue :D
