### ISSUE TITLE
MissingTraversableReturnTypeHintSpecification is not working with generics syntax

### ISSUE THREAD

**Issue by voku** [slevomat/coding-standard#522] opened 2018-10-15 21:05 UTC
example from PHPStan (https://github.com/phpstan/phpstan)

```php
	/**
	 * @return array<int, \PHPStan\Reflection\ParameterReflection>
	 */
	public function getParameters(): array;
```

**Comment by voku** [comment] 2018-10-15 21:09
(same for MissingTraversableParameterTypeHintSpecification)

**Comment by kukulich** [comment] 2018-10-16 04:39
Duplicate of #251

**Closed by kukulich** 2018-10-16 04:39 UTC
Labels: Duplicate
